name: build

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt

      - run: python dist.py

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
          commit_message: deploy ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
