name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: docker-compose up -d

      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt

      - name: wait mysql ready
        run: |
          timeout 30s grep -q 'MySQL init process done. Ready for start up.' <(docker-compose logs -f)
          timeout 30s grep -q 'ready for connections' <(docker-compose logs -f)

      - run: python test.py

      - run: docker-compose logs
        if: "${{ failure() }}"
